version: 2

jobs:
  lint:
    docker:
      - image: web3f/ci-commons:v1.8.0
    steps:
      - checkout
      - run:
          command: |
            helm lint ./charts/namespaces

  integrationTests:
    docker:
      - image: web3f/ci-commons:v1.8.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          description: run integration tests
          command: |
            /scripts/integration-tests.sh

  publishChart:
    docker:
      - image: web3f/ci-commons:v1.8.0
    steps:
      - checkout
      - run:
          command: |
            /scripts/publish-chart.sh

  deploy:
    docker:
      - image: web3f/ci-commons:v1.8.0
    steps:
      - checkout
      - run:
          environment:
            HELM_ENV: production
            GCP_REGION: europe-west3
          command: |
            /scripts/deploy.sh -c engineering

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/
      - integrationTests:
          filters:
            tags:
              only: /.*/
          requires:
            - lint
      - publishChart:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - integrationTests
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - publishChart
